Adding stage to path, fixing 'Try it out'
SamWSoftware/serverless-auto-swagger pull request #15
Opened 2022-01-24 19:08 UTC by NicoIamarino

I just added stage to url that will be used to 'Try it out'

2022-01-24 22:40 UTC, NicoIamarino commented
#4

2022-01-31 17:53 UTC, bfaulk96 approved these changes
This would be really nice – can't really use this package without it

2022-02-02 17:36 UTC, bfaulk96 commented
Also, I don't think this fixes #4 – they specifically need a basePath, not a stage, from the sounds of it.

2022-02-03 04:52 UTC, NicoIamarino commented
> Also, I don't think this fixes #4 – they specifically need a basePath, not a stage, from the sounds of it.

The URL generated by API Gateway includes the stage so to 'try it out' you moust use the same route

2022-02-05 11:22 UTC, SamWSoftware commented on src/ServerlessAutoSwagger.ts
> +            stagePath = stagePath ? `/${stagePath}` : ""
I think we can do this in a nicer way with a 'basePath' defined in the 'server' settings which are global to the whole API. 
https://swagger.io/specification/#server-object

2022-02-05 11:23 UTC, SamWSoftware requested changes
i think we can use base path in the server config to do this globally instead of in ever function

2022-02-08 21:45 UTC, bfaulk96 commented
@NicoIamarino @SamWSoftware https://github.com/SamWSoftware/serverless-auto-swagger/pull/32 should fix this in a slightly nicer way 😄

2022-02-08 22:41 UTC, bfaulk96 commented
Closing this, as Swagger's `basePath` has been implemented in 1.7.0 (which will be published soon hopefully)

2022-02-08 22:41 UTC, closed without merging